In [242]:
import numpy as np
import random
import matplotlib.pyplot as plt
import math
import ipywidgets as widgets
from ipywidgets import interact, interactive, fixed, interact_manual
import scipy
from scipy.stats import chisquare
import sys
import copy

In [243]:
exchange_rate_USD_EUR = 0.9

exchange_rate_GBP_EUR = 1.19

currency = ["EUR", "GBP", "USD"]


In [244]:
def generate_data(n):

    positions = np.zeros((n,3))

    for i in range(n):
        positions[i,0] = random.randint(-1000,1000)
        positions[i,1] = random.randint(1,3)
        
        if positions[i,1] == 3:
            positions[i,2] = random.randint(1,3) 
    
    
    '''
    positions = np.zeros((2,3))

    positions[0,0] = 1000
    positions[1,0] = -500

    positions[0,1] = 3
    positions[1,1] = 3

    positions[0,2] = 1
    positions[1,2] = 2
    '''

    print(positions)
    return positions


In [245]:
def settlementrisk(position):

    risk = 0
    mod = position[0].copy()
    if position[1] == 3:

        if position[2] == 1:
            mod *= exchange_rate_GBP_EUR
        elif position[2] == 2:
            mod *= exchange_rate_USD_EUR
    
        return max(0,float(mod))

    return max(0, float(mod))             
    


In [246]:
def BruteForce(positions):

    netting_GBP = np.zeros((0, 3))
    netting_USD = np.zeros((0, 3))
    netting_EUR = np.zeros((0, 3))
    remaining_impacts = np.zeros((0, 3))

    for i in range(len(positions)):

        if positions[i,2] == 3:
            row = copy.deepcopy(positions[i,:])
            netting_EUR = np.vstack([netting_EUR, row])
        elif positions[i,2] == 1:
            row = copy.deepcopy(positions[i,:])
            netting_GBP = np.vstack([netting_GBP, row])
        elif positions[i,2] == 2:
            row = copy.deepcopy(positions[i,:])
            netting_USD = np.vstack([netting_USD, row])
        else:
            row = copy.deepcopy(positions[i,:])
            remaining_impacts = np.vstack([remaining_impacts, row])

    
    return settlementrisk(np.array([np.sum(netting_GBP[:,0]), 3, 1])) + settlementrisk(np.array([np.sum(netting_USD[:,0]), 3, 2])) + settlementrisk(np.array([np.sum(netting_EUR[:,0]), 3, 3])) + settlementrisk(np.array([np.sum(remaining_impacts[:,0]),0,0]))


In [247]:
def Linearisation(positions):

    baseline = copy.deepcopy(positions[0,:])
    baseline_exposure = settlementrisk(baseline)
    total = baseline_exposure
    
    for i in range(len(positions)-1):

        row = copy.deepcopy(positions[i+1,:])

        if baseline[1] == row[1] and baseline[1] == 3.:

            if baseline[2] == row[2]:
                
                temp_netting = np.array([0,0,0])
                temp_netting = np.vstack([temp_netting, baseline])
                temp_netting = np.vstack([temp_netting, row])

                sum = np.sum(temp_netting[:,0])
                calc = settlementrisk(np.array([sum, 3, row[2]]))
                total += calc - baseline_exposure
            else:
                total += settlementrisk(row)

        else:
            total += settlementrisk(row)

    return total        

In [248]:
def Conservative(positions):

    total = 0
    for i in range(len(positions)):
        row = copy.deepcopy(positions[i,:])
        total += settlementrisk(row)
    
    return total


In [249]:
def Averages(positions):

    n = len(positions)-1
    baseline = copy.deepcopy(positions[0,:])
    baseline_exposure = settlementrisk(baseline)
    total = baseline_exposure
    
    for i in range(len(positions)-1):

        row = copy.deepcopy(positions[i+1,:])

        if baseline[1] == row[1] and baseline[1] == 3.:
            
            if baseline[2] == row[2]:

                temp_netting = np.array([0,0,0])
                temp_netting = np.vstack([temp_netting, baseline])
                temp_netting = np.vstack([temp_netting, row])
                temp_netting[2,0] *= n

                total += 1/n*(settlementrisk(np.array([np.sum(temp_netting[:,0]), 3, row[2]])) - baseline_exposure)
            else:
                row[0] *= n
                total += 1/n*settlementrisk(row)

        else:
            row[0] *= n
            total += 1/n*settlementrisk(row)

    return total

In [250]:
def sim(n):

    data = generate_data(n)

    total_BF = BruteForce(data)

    total_Linearisation = Linearisation(data)

    total_Conservative = Conservative(data)

    total_Averages = Averages(data)

    print("Brute Force: ", total_BF)
    print("\n")
    print("Linearisation: ", total_Linearisation)
    print("\n")
    print("Conservative: ", total_Conservative)
    print("\n")
    print("Averages: ", total_Averages)

In [241]:
sim(20)

[[-475.    1.    0.]
 [ 399.    2.    0.]
 [-381.    3.    3.]
 [ 393.    1.    0.]
 [-925.    3.    1.]
 [-594.    1.    0.]
 [-194.    3.    1.]
 [ 403.    3.    3.]
 [ 454.    1.    0.]
 [ 173.    3.    1.]
 [-814.    2.    0.]
 [-829.    3.    2.]
 [  36.    2.    0.]
 [ 815.    1.    0.]
 [ 921.    1.    0.]
 [ 715.    1.    0.]
 [-694.    3.    2.]
 [ 919.    2.    0.]
 [-565.    3.    2.]
 [-955.    1.    0.]]
Brute Force:  1836.0


Linearisation:  5260.87


Conservative:  5260.87


Averages:  5260.87
